import type { Batch, Settings, StockItem, StepKey, Templates } from './types';

const stepKeys: StepKey[] = ['step0','step1','step2','step3','step4','step5','step6'];
const emptyUrls = { step0:'', step1:'', step2:'', step3:'', step4:'', step5:'', step6:'' };
const chatNames = { step0:'イヌ式市場|買い目判定', step1:'イヌ式市場|X記事作成', step2:'イヌ式市場|X英語ポスト作成', step3:'イヌ式市場|note記事作成', step4:'イヌ式市場|X日本語ポスト作成', step5:'イヌ式市場|note画像指示書', step6:'イヌ式市場|X画像指示書' };
const defaultSettings: Settings = { defaultProjectUrl:'', projectUrlsByStep:emptyUrls, projectNamesByStep:chatNames, chatUrlsByStep:emptyUrls, chatNamesByStep:chatNames, step0ChatUrl:'', step1ChatUrl:'', step2ChatUrl:'', step3ChatUrl:'', step4ChatUrl:'', step5ChatUrl:'', step6ChatUrl:'', appendOutputRulesToInput:false, favoriteCommands:['ランダム　実行','ランダムヨシ　実行','ランダム高配当　実行','ランダムテーマ株　実行','ランダムモメンタム　実行','ランダム半導体　実行','ランダムAI　実行','ランダム不動産　実行'] };
const defaultTemplates: Templates = { step0_buyJudgmentPrompt:'', step1_xArticlePrompt:'', step2_overseasXPostPrompt:'', step3_noteArticlePrompt:'', step4_japaneseXPostPrompt:'', step5_noteImagePrompt:'', step6_xImagePrompt:'' };
const storageKey = 'inu-market-semi-auto-ui:v2';

type LocalData = { batches: Batch[]; settings: Settings; templates: Templates };
function normalizeSettings(settings: Partial<Settings> = {}): Settings { const urls = { ...defaultSettings.chatUrlsByStep, ...(settings.projectUrlsByStep ?? {}), ...(settings.chatUrlsByStep ?? {}) }; const names = { ...defaultSettings.chatNamesByStep, ...(settings.projectNamesByStep ?? {}), ...(settings.chatNamesByStep ?? {}) }; return { ...defaultSettings, ...settings, projectUrlsByStep: urls, projectNamesByStep: names, chatUrlsByStep: urls, chatNamesByStep: names, step0ChatUrl: urls.step0, step1ChatUrl: urls.step1, step2ChatUrl: urls.step2, step3ChatUrl: urls.step3, step4ChatUrl: urls.step4, step5ChatUrl: urls.step5, step6ChatUrl: urls.step6, favoriteCommands: settings.favoriteCommands?.length ? settings.favoriteCommands : defaultSettings.favoriteCommands, appendOutputRulesToInput: Boolean(settings.appendOutputRulesToInput) }; }
function loadLocal(): LocalData { try { const raw = localStorage.getItem(storageKey); if (raw) { const parsed = JSON.parse(raw); return { batches: parsed.batches ?? [], settings: normalizeSettings(parsed.settings), templates: { ...defaultTemplates, ...(parsed.templates ?? parsed.promptTemplates ?? {}) } }; } } catch { /* ignore localStorage parse errors */ } return { batches: [], settings: defaultSettings, templates: defaultTemplates }; }
function saveLocal(data: Partial<LocalData>) { const current = loadLocal(); localStorage.setItem(storageKey, JSON.stringify({ ...current, ...data })); }
function mirror(url: string, data: any) { if (url.includes('/api/batches') && Array.isArray(data)) saveLocal({ batches:data }); if (url.endsWith('/api/settings')) saveLocal({ settings:normalizeSettings(data) }); if (url.endsWith('/api/templates')) saveLocal({ templates:data }); return data; }
async function json<T>(url: string, init?: RequestInit): Promise<T> { const res = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers||{}) } }); const data = await res.json(); if (!res.ok) throw new Error(data.error || res.statusText); return mirror(url, data) as T; }
async function serverOrLocal<T>(server:()=>Promise<T>, local:()=>T|Promise<T>) { try { return await server(); } catch { return local(); } }
function now() { return new Date().toISOString(); }
function makeBatch(command:string, stocks:StockItem[] = []): Batch { return { batchId:`local-${Date.now()}-${Math.random().toString(36).slice(2,8)}`, createdAt:now(), command, status: stocks.length ? 'partial' : 'draft', stocks, logs:[] }; }
function parseJudgmentText(text:string): StockItem[] { const allowed = new Set(['ヨシ(盤石)╰( Ｕ ・ω・)','ヨシ(期待先行)╰( Ｕ ・ω・)','待て(有望)╰( Ｕ ・ω・)','待て(絶望)╰( Ｕ ・ω・)']); return text.replace(/\r\n/g,'\n').split(/\n\s*\n/g).map((b)=>b.trim()).filter(Boolean).flatMap((block,index)=>{ const lines = block.split('\n').map((l)=>l.trim()).filter(Boolean); const m = lines[0]?.match(/^(.+)\s+([A-Za-z0-9.\-]+)$/); if (lines.length !== 3 || !m || !allowed.has(lines[2])) return []; return [{ stockId:`local-stock-${Date.now()}-${index}-${Math.random().toString(36).slice(2,8)}`, name:m[1].trim(), code:m[2].trim(), priceLine:lines[1], judgment:lines[2], rawJudgmentText:lines.join('\n'), xArticle:'', overseasXPost:'', noteArticle:'', japaneseXPostMain:'', noteImagePrompt:'', xImagePrompt:'', statusByStep:{ step0:'manual', step1:'pending', step2:'pending', step3:'pending', step4:'pending', step5:'pending', step6:'pending' }, errorByStep:{}, updatedAt:now() } as StockItem]; }); }
function inputText(step:StepKey, stock?:StockItem, command='') { if (step === 'step0') return command.trim(); if (!stock) return ''; return (step === 'step1' || step === 'step2' || step === 'step3') ? stock.rawJudgmentText.trim() : stock.noteArticle.trim(); }
function findStock(data:LocalData, stockId:string) { for (const batch of data.batches) { const stock = batch.stocks.find((s)=>s.stockId===stockId); if (stock) return { batch, stock }; } throw new Error('銘柄が見つかりません。'); }
export const api = {
  health: () => serverOrLocal(() => json<any>('/api/health'), () => ({ mode:'browser localStorage mode', localIp: location.hostname })),
  batches: () => serverOrLocal(() => json<Batch[]>('/api/batches'), () => loadLocal().batches),
  batch: (id:string) => serverOrLocal(() => json<Batch>(`/api/batches/${id}`), () => loadLocal().batches.find((b)=>b.batchId===id)!),
  manualImport: (text:string, command='手動取り込み', batchId?:string) => serverOrLocal(() => json<Batch>('/api/batches/manual-import', { method:'POST', body:JSON.stringify({ text, command, batchId }) }), () => { const data=loadLocal(); const stocks=parseJudgmentText(text); let batch:Batch; if (batchId) { batch = data.batches.find((b)=>b.batchId===batchId)!; batch.stocks=[...batch.stocks,...stocks]; } else { batch=makeBatch(command, stocks); data.batches.unshift(batch); } saveLocal({ batches:data.batches }); return batch; }),
  createFromCommand: (command:string) => serverOrLocal(() => json<Batch>('/api/batches/create-from-command', { method:'POST', body:JSON.stringify({ command }) }), () => { const data=loadLocal(); const batch=makeBatch(command.trim()); data.batches.unshift(batch); saveLocal({ batches:data.batches }); return batch; }),
  buildCopyText: (body:{ step:StepKey; stockId?:string; command?:string }) => serverOrLocal(() => json<any>('/api/build-copy-text', { method:'POST', body:JSON.stringify(body) }), () => { const data=loadLocal(); const stock=body.stockId ? findStock(data, body.stockId).stock : undefined; const input=inputText(body.step, stock, body.command); const settings=data.settings; return { initializationText:'', inputText:input, projectUrl:settings.chatUrlsByStep[body.step] || '', projectName:settings.chatNamesByStep[body.step], warning: body.step !== 'step0' && !input ? (['step1','step2','step3'].includes(body.step) ? '3行判定コードがありません。先に工程0の判定を取り込んでください。' : 'note記事がありません。先に工程3を作成・保存してください。') : '' }; }),
  saveStock: (stockId:string, body:any) => serverOrLocal(() => json<Batch>(`/api/stocks/${stockId}/save`, { method:'POST', body:JSON.stringify(body) }), () => { const data=loadLocal(); const found=findStock(data, stockId); (found.stock as any)[body.field] = body.value ?? ''; if (body.step) (found.stock.statusByStep as any)[body.step] = body.markCopied ? 'copied' : ((body.value ?? '').trim() ? (body.step === 'step0' ? 'manual' : 'done') : 'pending'); found.stock.updatedAt=now(); saveLocal({ batches:data.batches }); return found.batch; }),
  settings: () => serverOrLocal(() => json<Settings>('/api/settings'), () => loadLocal().settings),
  saveSettings: (body:any) => serverOrLocal(() => json<Settings>('/api/settings/save', { method:'POST', body:JSON.stringify(body) }), () => { const settings=normalizeSettings(body); saveLocal({ settings }); return settings; }),
  templates: () => serverOrLocal(() => json<Templates>('/api/templates'), () => loadLocal().templates),
  saveTemplates: (body:any) => serverOrLocal(() => json<Templates>('/api/templates/save', { method:'POST', body:JSON.stringify(body) }), () => { const templates={...defaultTemplates,...body}; saveLocal({ templates }); return templates; }),
  export: (kind:string) => serverOrLocal(() => json<any>('/api/export', { method:'POST', body:JSON.stringify({ kind }) }), () => { const data=loadLocal(); const payload:any={}; if (kind==='all'||kind==='batches') payload.batches=data.batches; if (kind==='all'||kind==='settings') { payload.settings=data.settings; payload.favoriteCommands=data.settings.favoriteCommands; payload.chatUrlsByStep=data.settings.chatUrlsByStep; } if (kind==='all'||kind==='templates') payload.templates=data.templates; return payload; }),
  import: (body:any) => serverOrLocal(() => json<any>('/api/import', { method:'POST', body:JSON.stringify(body) }), () => { const data=loadLocal(); saveLocal({ batches: body.batches ? (body.importMode==='append' ? [...data.batches, ...body.batches] : body.batches) : data.batches, settings: body.settings ? normalizeSettings({ ...body.settings, favoriteCommands: body.favoriteCommands ?? body.settings.favoriteCommands }) : data.settings, templates: body.templates ?? body.promptTemplates ?? data.templates }); return { ok:true }; })
};
